export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const GET_VITAMIN_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_AYURVEDA_SUCCESS = 'GET_AYURVEDA_SUCCESS'
export const GET_SUPPLEMENTS_SUCCESS = 'GET_SUPPLEMENTS_SUCCESS';
export const GET_TEST_TRIP_SUCCESS = 'GET_TEST_TRIP_SUCCESS';