export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL";
export const GET_VITAMIN_SUCCESS="GET_VITAMIN_SUCCESS"
export const GET_AYURVEDA_SUCCESS="GET_AYURVEDA_SUCCESS"
export const GET_TESTSTRIP_SUCCESS="GET_TESTSTRIP_SUCCESS"
export const GET_SUPLIMENT_SUCCESS="GET_SUPLIMENT_SUCCESS"